sudo: false

language: php

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=nightly
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
  fast_finish: true
  allow_failures:
    - php: 7.2

branches:
  only:
    - master
    - dev